import dotenv from "dotenv";

dotenv.config();

export const envVariable = {
  PORT: process.env.PORT!,
  MONGODB_LOCALHOST: process.env.MONGODB_LOCALHOST!,
  TOKEN_SECRET: process.env.TOKEN_SECRET!,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET!,
  JWT_EXPIRES: process.env.JWT_EXPIRES!,
  ACCESS_TOKEN_SECRET_KEY: process.env.ACCESS_TOKEN_SECRET_KEY!,
  REFRESH_TOKEN_SECRET_KEY: process.env.REFRESH_TOKEN_SECRET_KEY!,
  ACCESS_TOKEN_KEY_EXPIRE_TIME: process.env.ACCESS_TOKEN_KEY_EXPIRE_TIME!,
  REFRESH_TOKEN_KEY_EXPIRE_TIME: process.env.REFRESH_TOKEN_KEY_EXPIRE_TIME!,
  RESET_PASSWORD_EXPIRE_TIME: process.env.RESET_PASSWORD_EXPIRE_TIME!,
  JWT_ISSUER: process.env.JWT_ISSUER!,
  WEBSITE_URL: process.env.WEBSITE_URL!,
  GOOGLE_SECRET: process.env.GOOGLE_SECRET as string,
  GOOGLE_ID: process.env.GOOGLE_ID as string,
  GOOGLE_REFRESHTOKEN: process.env.GOOGLE_REFRESHTOKEN as string,
  GOOGLE_REDIRECT: process.env.GOOGLE_REDIRECT as string,
  PASSPORT_GOOGLE_CLIENT_ID: process.env.PASSPORT_GOOGLE_CLIENT_ID as string,
  PASSPORT_GOOGLE_CLIENT_SECRET: process.env
    .PASSPORT_GOOGLE_CLIENT_SECRET as string,
};
